[build]
  publish = "dist/"
  command = "elm make src/Main.elm --output=dist/index.html"

[build.environment]
  ELM_HOME = "$NETLIFY_BUILD_BASE/cache/elm"

[[redirects]]
  from = "/.+"
  to = "/"
  status = 301
  force = false
